### ISSUE TITLE
Node engine version

### ISSUE THREAD

**Issue by tobysmith568** [deitch/smtp-tester#30]
Hey. I've updated to version 2.0.0 and I'm now seeing warnings in my CI runs:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'smtp-tester@2.0.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.11.0' }
npm WARN EBADENGINE }
```

[I can see that as a part of the v2 release you've upped the required node version to 18](https://app.renovatebot.com/package-diff?name=smtp-tester&from=1.2.0&to=2.0.0) - which explains why I'm now getting this error because in my CI I'm using a whole range of versions that go as low as 14.

Does smtp-tester actually require node 18 or higher? I assume it works fine on node 14 and 16 too?
If it doesn't specifically need node 18 would you consider lowering the requirement? Especially as Node 14 and 16 are still in LTS support and [production apps should not yet be using node 18 until October 25th](https://nodejs.org/en/about/releases/#:~:text=Production%20applications%20should%20only%20use%20Active%20LTS%20or%20Maintenance%20LTS%20releases).

Thanks!

**Comment by tobysmith568** [comment]
Hey @deitch,

Since raising this issue I've now found PR #27. However, I'm still confused about what prompted the Node 18 requirement? I don't see anything in [the diff between 1.2.0 and 2.0.0](https://app.renovatebot.com/package-diff?name=smtp-tester&from=1.2.0&to=2.0.0) that requires Node 18 specifically?

I'm using `smtp-tester` 2.0.0 on Node 14 and Node 16 seemingly fine. (Except for the warning)

Hoping you can shed some light on this? Thanks :)

**Comment by deitch** [comment]
I don't recall all of the details, but the part I do remember, based on that PR, is that those updated dependencies do require it. Although now that I look at their `package.json` files for those tagged versions in GitHub, I don't see it. I see smtp-server requires node >=6.0.0, so that isn't it.

@anton-johansson , you did that PR #27 ; do you recall why it was necessary?

**Comment by tobysmith568** [comment]
I'm happy to be corrected, but I don't think that a package maintainer needs to keep track of their dependencies and ensure that the node version requirement in their package.json satisfies all of them.

I'm under the impression that if one of your deps were to have a node version constraint in their package.json then I would get a warning on install that my codebase isn't compatible with that dependency specifically.

I believe that the `engines` field in your package.json only applies to your usages of node.js imports. From what I can see, smtp-tester only uses a `path` import to use the [join method](https://github.com/deitch/smtp-tester/blob/master/lib/index.js#L70), but that api has existed for many node versions now, so I believe you can set your node version requirement quite low.

The docs are unclear at best, but they do refer to ["your stuff"](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines:~:text=of%20node%20that-,your%20stuff,-works%20on%3A).

**Comment by deitch** [comment]
> but I don't think that a package maintainer needs to keep track of their dependencies and ensure that the node version requirement in their package.json satisfies all of them

I have been in "DLL hell" with node, go, Java, etc. etc. for far too many years. I fully expect that any package system I deal with eventually will make my life impossible. The very idea that I do **not** need to keep track of it seems impossible to me. 😆 

So what are you suggesting? That we can set the engines constraint very low? So why did we need to bump it to 18.0.0 for that PR?

**Comment by tobysmith568** [comment]
OK, so I've run a small test locally. From what I can see, it looks like Node.js engine constraints don't bubble up. They only warn those who are direct dependencies. Which goes against what I thought previously.

So yeah, you do need to be careful about the engine constraints applied by your dependencies and set your own one carefully to protect those who install `smtp-tester`.

However, I've looked though your `package-lock.json` file and the highest engine constraint in there is [`10.23.2` for `iconv-lite`](https://github.com/deitch/smtp-tester/blob/master/package-lock.json#L267). Nothing seems to need something greater than that.

The `path.join` Node.js API that `smtp-tester` uses pre-dates `10.23.2` so I would say you don't need to go any higher than that.

If #27 does _require_ Node.JS 18 (I don't think it does) then I would suggest you back it out.  
Node 14 is supported for production use until 2023-04-30, and Node 16 is supported until 2023-09-11.

If #27 doesn't require Node.JS 18 then I would lower your own requirement. 10.x seems a little extreme to me as that long out of support, but >=14 would seem reasonable to me.

**Comment by deitch** [comment]
Go for it. Open a PR for 14 then.

**Comment by anton-johansson** [comment]
Sorry for the late reply. As you can see in #25, I was having problems when running it on Node.js 18. I cannot remember the exact details for why 18 would be required after bumping the dependencies `mailparser` and `smtp-server`, but I remember struggling quite a bit with it. If this was wrong, then I apologize!

**Comment by deitch** [comment]
No problem. If I had the time - and this weren't completely FOSS volunteer - I would set up GitHub Actions to run tests with a matrix across multiple nodejs versions.

**Comment by tobysmith568** [comment]
@deitch - want a PR for one of those?
