### ISSUE TITLE
Codebase could use some maintenance

### ISSUE THREAD

**Issue by djanowski** [deitch/smtp-tester#7]
I was trying to fix an issue but found I couldn't do it because:

* `nodeunit >= 0.8.1` is very broad, you get a version incompatible with this project.
* Installing `nodeunit@0.8.1` doesn't work either, probably nested dependencies or unsupported Node version by that `nodeunit` version.
* No `npm test` script. The one in `package.json` (old format?) points to a non-existing `test2.js` file.

I like the simplicity of this library, I don't think the last commit being 1.5 years old is a problem. However, software erosion is a problem, so I suggest to set up Travis CI or similar to help keep the library up to date.

**Comment by deitch** [comment]
Great issues. Yeah, worth dealing with... somehow I have to find a way to have OSS support my living, rather than chewing up into real work time that pays the bills. When I figure it out.... :-)

Funny, I haven't used nodeunit in years. This just needs some real cleanup.

**Comment by djanowski** [comment]
Would you take PRs?

**Comment by deitch** [comment]
YES!!!!'nm

**Comment by deitch** [comment]
Thanks for the PR. Merged in.
