### ISSUE TITLE
Message ID passed to handler is off by one

### ISSUE THREAD

**Issue by djanowski** [deitch/smtp-tester#8]
Offending snippet:

```js
msgs[msgid++] = email;
processMsg(email,msgid);
```

This means that if you try to `remove` by the ID you just got, nothing actually happens.

Also, might be worth throwing an error if the message ID doesn't exist when you call `remove`.

I tried to fix this issue myself and submit a PR, but #7.

**Comment by djanowski** [comment]
Update: this happens when the handler is set up before the message arrives. If you `bind` it afterwards, `smtp-tester` loops through existing messages and invokes the handler with the right message ID.

**Comment by deitch** [comment]
Well, crap. That is pretty surprising. But, yes, I can see it is the problem because we do `msg++` instead of `++msg`. I will pull in that PR immediately. 

On the other hand, if this isn't a perfect example of evolving software. You found a bug, wrote a test to prove it, then fixed it... and the test is almost 30 lines while the change is 1-2.

**Comment by deitch** [comment]
Merged in with a minor change. Thank you again for the PR!

Would love to hear what you are using it for. Would offer to have coffee/tea, but haven't been in Buenos Aires in a decade.

**Comment by djanowski** [comment]
Thank you for looking at this so quickly and cutting a release. 

We use it at @broadly to test our emails.

Shavua tov!

**Comment by deitch** [comment]
> ... at @broadly

That looks pretty cool. Too many startups focused on CRM or big data or whatever for "elephants", nice to see the real focus on SMB coming from places like Broadly.

Wait a minute... Assaf! Assaf is your CTO? I know him! We did work on his zombiejs. Send warmest regards.

> Shavua tov!

And to you! I knew a Janowski from Toronto many years ago, any relation? Really should take this off the comment thread, shouldn't we? I will drop an email to the address on https://github.com/djanowski

**Comment by deitch** [comment]
> Thank you for looking at this so quickly and cutting a release.

You are welcome. I had a window, I just grabbed it (to the dismay, I am sure, of the open issues in jstree-grid, but.... ). And I have to say, smtp-tester has led to at least 2 consulting projects directly (one of which led to https://github.com/deitch/imapper ), and several indirect.
